const BOOKS = [
  { id: "b1", title: "The Lost Library", author: "A. Reader", price: 12.99, genre: "fiction", img: "https://m.media-amazon.com/images/I/91uFyvEVSeL._AC_UF1000,1000_QL80_.jpg", description: "A thrilling story about a hidden library of ancient secrets, and the young historian who risks everything to find it." },
  { id: "b2", title: "Starlight Journey", author: "M. Voyager", price: 15.50, genre: "fantasy", img: "https://m.media-amazon.com/images/I/81xpdYjqb2L._AC_UF1000,1000_QL80_.jpg", description: "A fantasy adventure across galaxies, where a reluctant hero must wield cosmic magic to save her home from a dark entity." },
  { id: "b3", title: "Mystery of the Clock", author: "C. Sleuth", price: 9.99, genre: "mystery", img: "https://m.media-amazon.com/images/I/91iIvH-exYL._AC_UF350,350_QL50_.jpg", description: "A classic detective mystery set in a fog-laden town, where every tick of the clock tower brings a new, chilling clue." },
  { id: "b4", title: "Thoughts & Theory", author: "D. Thinker", price: 18.00, genre: "non-fiction", img: "https://m.media-amazon.com/images/I/61L16HkXXAL._AC_UF1000,1000_QL80_.jpg", description: "A collection of profound essays exploring the intersection of modern science, philosophy, and the human experience." },
  { id: "b5", title: "Forest Tales", author: "E. Green", price: 11.25, genre: "fiction", img: "https://m.media-amazon.com/images/I/91X3zzVPvAL._AC_UF1000,1000_QL80_.jpg", description: "A charming collection of short tales from an enchanted forest, where animals talk and ancient trees hold forgotten wisdom." },
  { id: "b6", title: "Deep Magic", author: "F. Mage", price: 13.75, genre: "fantasy", img: "https://m.media-amazon.com/images/I/71t3XlBI2GL._AC_UF1000,1000_QL80_.jpg", description: "In a world where magic is fading, a young sorceress must delve into forbidden arts to prevent a catastrophic magical apocalypse." },
  { id: "b7", title: "The Hidden Clue", author: "G. Detective", price: 10.50, genre: "mystery", img: "https://m.media-amazon.com/images/I/81kL3StVBoL._SY522_.jpg", description: "A detective is drawn into a web of deceit when a seemingly simple case reveals a conspiracy that reaches the city's elite." },
  { id: "b8", title: "Science Simplified", author: "H. Scholar", price: 20.00, genre: "non-fiction", img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTlHVJU7WqdD8499pCbSKQWZtrchw0T3Q6B4PFtgkz2i0rObsaS9vlI_e7zkmIO_60nRbBeFLuVpKN9z83jH9O2KEI0DCpj-b6PNSbxMD0", description: "An accessible guide to complex scientific concepts, from quantum physics to genetics, made easy for everyone to understand." },
  { id: "b9", title: "Ocean's Whisper", author: "I. Sailor", price: 14.30, genre: "fiction", img: "https://m.media-amazon.com/images/I/710POOREJIL._SY522_.jpg", description: "A haunting tale of a lighthouse keeper who discovers a mysterious connection to the sea and a legendary ghost ship." },
  { id: "b10", title: "Realm of Dragons", author: "J. Knight", price: 16.45, genre: "fantasy", img: "https://m.media-amazon.com/images/I/91b0C2YNSrL._AC_UF1000,1000_QL80_.jpg", description: "A young knight forms an unlikely bond with a dragon, and together they must unite warring kingdoms against a common enemy." },
  { id: "b11", title: "The Silent Witness", author: "K. Investigator", price: 12.80, genre: "mystery", img: "https://m.media-amazon.com/images/I/81OthjkJBuL._AC_UF1000,1000_QL80_.jpg", description: "The only witness to a high-profile murder is a parrot. A skeptical investigator must learn to interpret the bird's clues." },
  { id: "b12", title: "History Unveiled", author: "L. Historian", price: 22.00, genre: "non-fiction", img: "https://m.media-amazon.com/images/I/41PKhphW7WL._SX342_SY445_FMwebp_.jpg", description: "A deep dive into forgotten moments of history, revealing the surprising stories and unsung heroes that shaped our world." }
];